services:
  - type: web
    name: kinetic-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 # Match your local version
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: SECRET_KEY
        generateValue: true
