"""
Django settings for Portbackend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vxd3ny&%$-x%*5_vgp_2#v7-oh==3yfcnios3e2i11%@crw)xc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

if "DATABASE_URL" in os.environ:
    DATABASES["default"] = dj_database_url.config(conn_max_age=600)

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "portfolio",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Portbackend.urls"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # Add your production React domain here later
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Portbackend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# backend/settings.py

from django.urls import reverse_lazy  # Add this import at the top of your settings file

# ... existing settings ...
UNFOLD = {
    "SITE_TITLE": "Kinetic_Env Backend",
    "SITE_HEADER": "Terminal Admin",
    "SITE_URL": "/",
    "SITE_SYMBOL": "terminal",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    # Injecting our custom Libadwaita CSS
    "STYLES": [
        lambda request: static("css/libadwaita.css"),
    ],
    # Material You Monochrome Olive Green Scale
    "COLORS": {
        "primary": {
            "50": "#f4f6e9",  # Appears on lightest backgrounds
            "100": "#e2e6d5",  # Surface variants
            "200": "#cee7b4",  # Primary containers (Light Mode)
            "300": "#b6dc97",
            "400": "#a5d27e",  # <-- DARK MODE PRIMARY (Glowing Olive)
            "500": "#8bc05c",
            "600": "#6ea640",
            "700": "#55842f",
            "800": "#435033",  # <-- LIGHT MODE PRIMARY (Deep Olive)
            "900": "#2e3823",  # Primary containers (Dark Mode)
            "950": "#161d10",  # Appears on darkest backgrounds
        },
    },
    # Libadwaita / System Settings structured Sidebar
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "System Registry",
                "separator": True,
                "items": [
                    {
                        "title": "Projects",
                        "icon": "folder",
                        "link": reverse_lazy("admin:portfolio_project_changelist"),
                    },
                    {
                        "title": "Skills",
                        "icon": "code",
                        "link": reverse_lazy("admin:portfolio_skill_changelist"),
                    },
                    {
                        "title": "Services",
                        "icon": "monitor",
                        "link": reverse_lazy("admin:portfolio_service_changelist"),
                    },
                ],
            },
            {
                "title": "User Modules",
                "separator": True,
                "items": [
                    {
                        "title": "Experience",
                        "icon": "work",
                        "link": reverse_lazy("admin:portfolio_experience_changelist"),
                    },
                    {
                        "title": "Education",
                        "icon": "school",
                        "link": reverse_lazy("admin:portfolio_education_changelist"),
                    },
                    {
                        "title": "API Certifications",
                        "icon": "workspace_premium",
                        "link": reverse_lazy("admin:portfolio_certificate_changelist"),
                    },
                ],
            },
            {
                "title": "Comms",
                "separator": True,
                "items": [
                    {
                        "title": "Secure Uplinks",
                        "icon": "mail",
                        "link": reverse_lazy("admin:portfolio_contact_changelist"),
                    },
                ],
            },
        ],
    },
}
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 465  # CHANGED from 587
EMAIL_USE_SSL = True
# EMAIL_USE_TLS = True

# The email address that will SEND the notification
EMAIL_HOST_USER = "ansarimohammed122@gmail.com"

# CRITICAL: Do NOT use your real Gmail password here.
# You must generate a 16-character "App Password" in your Google Account settings.
EMAIL_HOST_PASSWORD = "qoaf mcsd jans idns"

# The email address where you want to RECEIVE the notifications
# (This can be the exact same address as EMAIL_HOST_USER)
ADMIN_EMAIL = "ansarimohammed122@gmail.com"
