# Generated by Django 6.0.3 on 2026-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for the blog card')),
                ('content', models.TextField(help_text='Paste Markdown content here')),
                ('cover_image', models.URLField(blank=True, help_text='Image URL from Unsplash or Imgur', max_length=500)),
                ('tags', models.CharField(help_text='Comma-separated tags (e.g. React, Django, API)', max_length=200)),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes')),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
