# Generated by Django 6.0.3 on 2026-03-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_github_url_project_live_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, help_text="URL or '#' if private/not available", max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.CharField(blank=True, help_text="URL or '#' if not deployed", max_length=500),
        ),
    ]
